config/urls.py
# -*- coding: utf-8 -*-


from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf import settings # new
from  django.conf.urls.static import static #new

# fix problem with admin section being inacessible on production
# https://github.com/pydanny/cookiecutter-django/issues/162
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include(('jsnetwork_project.users.urls','users'), namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^nameviewer/', include(('nameviewer.urls', 'nameviewer'), namespace='nameviewer')),
    url(r'^usermgmt/', include(('usermgmt.urls', 'usermgmt'), namespace='usermgmt')),
    url(r'^pdftools/', include(('pdftools.urls', 'pdftools'), namespace='pdftools')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

# set properties on the admin site - no need to define a custom template any more
# http://stackoverflow.com/questions/4938491/django-admin-change-header-django-administration-text
admin.site.site_header = 'Judgment Search Network Administration'
admin.site.site_title = 'JSN Admin'

jsnetwork_project/users/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

orders/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^order_new/', views.order_new, name='order_new'),
    url(r'^(?P<order_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^quick_search/', views.quick_search, name='quick_search'),
    url(r'^quick_order/', views.quick_order, name='quick_order'),
    url(r'^run_search/(?P<order_id>[0-9]+)/(?P<report_type>\w+)/$', views.run_search, name='run_search'),
    url(r'^settings/', views.settings, name='settings'),
    url(r'^view_pdf/(?P<filename>.+)$', views.view_report, name="view_report"),
    url(r'^xml-to-base64/$', views.xml_to_base64, name="xml_to_base64"),
    url(r'^csv_report/(?P<order_id>.+)$', views.csv_report, name="csv_report"),
    url(r'^csv_report_high_value/(?P<order_id>.+)$', views.csv_report_high_value, name="csv_report_high_value"),
    url(r'^merge_and_view/(?P<order_id>[0-9]+)/(?P<report_type>\w+)$', views.merge_and_view_pdf, name="merge_and_view"),
    url(r'^order_status/(?P<order_id>[0-9]+)/(?P<report_type>\w+)$', views.order_status, name='order_status'),
    url(r'^reorder/(?P<order_id>[0-9]+)$', views.reorder, name='reorder'),
    url(r'^name_select/(?P<order_id>[0-9]+)$', views.select_names, name='name_select'),
    url(r'^name_select_view_pdf/', views.name_select_view_pdf, name='name_select_view_pdf'),
    url(r'^search_prev/', views.search_prev, name='search_prev'),
]

pdftools/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^results_comparison/(?P<order_id>.+)$', views.results_comparison, name="results_comparison"),
    url(r'^cj_comparison/', views.cj_comparison, name="cj_comparison"),
    url(r'^make_pdf/v1/reports', views.make_pdf, name="make_pdf"),
    url(r'^make_pdf/v1/version', views.pdf_version, name="pdf_version")
]

jsnetwork_project/users/models.py
# -*- coding: utf-8 -*-


from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

orders/models.py
# noinspection PyPackageRequirements


from django.db import models

from core.models import TimeStampedModel


# Create your models here.
class Client(models.Model):
    """
    A class for representing a client model
    """
    client_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    client_id = models.CharField(max_length=50, blank=True)  # quickbooks number
    addr1 = models.CharField(max_length=100, blank=True, default=None, null=True)
    addr2 = models.CharField(max_length=100, blank=True, default=None, null=True)
    city = models.CharField(max_length=50, blank=True, default=None, null=True)
    state = models.CharField(max_length=2, blank=True, default=None, null=True)
    zip = models.CharField(max_length=10, blank=True, default=None, null=True)

    def __str__(self):
        return self.client_name


class Order(TimeStampedModel):
    """
    A simple class for representing an order in the system
    """
    EMAIL = 'EM'
    WEB_SERVICES = 'WB'
    TELEPHONE = 'TL'
    ORDER_SOURCE_CHOICES = (
        (EMAIL, 'Email'),
        (TELEPHONE, 'Telephone'),
        (WEB_SERVICES, 'Web Services'),
    )
    order_method = models.CharField(max_length=2, choices=ORDER_SOURCE_CHOICES, default=EMAIL)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)  # each order is reference to a single client
    title_number = models.CharField(max_length=20, verbose_name='Client file number')
    is_reorder = models.BooleanField(default=False)
    internal_tracking_num = models.CharField(max_length=100, blank=True, verbose_name='Internal number')
    date_invoiced = models.DateField(blank=True, default=None, null=True)


    def date_ordered(self):
        return self.created
    date_ordered.short_description = "Date ordered"

    def __str__(self):
        return self.title_number


class GeneratedReport(models.Model):
    """
    A simple class for representing generated reports in the system
    """
    bankruptcy_filename = models.CharField(max_length=255)
    usdc_filename = models.CharField(max_length=255)
    state_filename = models.CharField(max_length=255)
    state_hv_filename = models.CharField(max_length=255, default=None, null=True)
    cover_filename = models.CharField(max_length=255, blank=True, default=None, null=True)
    docket_list_filename = models.CharField(max_length=255, blank=True, default=None, null=True)
    patriot_filename = models.CharField(max_length=1000, blank=True, default=None, null=True)
    merged_report_filename = models.CharField(max_length=255, blank=True)
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE) # each generated report is references to a single order
    num_bankruptcy_matches = models.IntegerField(blank=True, default=None, null=True)
    num_usdc_matches = models.IntegerField(blank=True, default=None, null=True)
    num_state_matches = models.IntegerField(blank=True, default=None, null=True)
    num_state_hv_matches = models.IntegerField(blank=True, default=None, null=True)
    num_patriot_matches = models.IntegerField(blank=True, default=None, null=True)
    name_select_ready = models.CharField(max_length=1, blank=True, default=None, null=True)

    def __str__(self):
        return "Reports generated (b,u,s,p): {} - {} - {}".format(self.bankruptcy_filename, self.usdc_filename,
                                                                  self.state_filename, self.patriot_filename)


class SearchName(models.Model):
    """
    A class for representing the data supplied by a client for a judgment search
    """
    order = models.ForeignKey(Order, on_delete=models.CASCADE) # each search name is referenced to a single order
    first_name = models.CharField(max_length=100, blank=True, verbose_name='First Name')
    middle_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    suffix = models.CharField(max_length=20, blank=True)
    is_company = models.BooleanField(default=False)
    company_name = models.CharField(max_length=100, blank=True)
    company_type = models.CharField(max_length=20, blank=True) # make a choice
    address1 = models.CharField(max_length=100, blank=True)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    zip = models.CharField(max_length=10, blank=True)
    search_from = models.DateField()
    search_to = models.DateField()
    name_qualifier = models.CharField(max_length=20, blank=True)
    exact_name_match = models.BooleanField(default=False)
    additional_notes = models.TextField(blank=True)
    report_name = models.CharField(max_length=100, blank=True)
    high_value_search = models.BooleanField(default=False)
    
    def __unicode__(self):
        from collections import defaultdict
        if self.first_name != "":
            name = "{} {} {}".format(self.first_name, self.middle_name, self.last_name)
        elif self.company_name != "":
            name = self.company_name
        return name
    
    def __str__(self):
        from collections import defaultdict
        if self.first_name != "":
            name = "{} {} {}".format(self.first_name, self.middle_name, self.last_name)
        elif self.company_name != "":
            name = self.company_name
        return name

# namesearch models
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.


class NameBase(models.Model):
    """
    A class for representing a forename or surname as provided by IMage Partners
    Specifying an arbitrary column as a primary key since this is a readonly table
    """
    name = models.CharField(max_length=255)
    name_match = models.CharField(max_length=255, primary_key=True)
    score = models.DecimalField(max_digits=10, decimal_places=0)
    deleted = models.CharField(max_length=1)
    nickname = models.CharField(max_length=1)

    class Meta:
        managed = False
        abstract = True
        ordering = ['name']


class Forename(NameBase):
    """
    A class for representing forenames as provided by the name alias database
    """
    class Meta(NameBase.Meta):
        db_table = 'forenames'


class Surname(NameBase):
    """
    A class for representing surnames as provided by the name alias database
    """
    class Meta(NameBase.Meta):
        db_table = 'surnames'


class UserClient(models.Model):
    """
    A custom django user model which provides some additional flexibility not present in the base model
    Much easier to override this at the beginning of the app's development than trying to retrofit something in later on!
    """
    from config.settings.common import AUTH_USER_MODEL as user_model
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(user_model, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.user.username + " - " + self.client.client_name


class FilteredSearchNameList(models.Model):
    """
    Unused
    """
    name_list = models.TextField()
    date_created = models.DateField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)  # each filtered name list was generated based on an order
    name_search = models.CharField(max_length=255, db_index=True)  # this is the original name entered by the user


class NameReportHistory(models.Model):
    """
    A model for mapping the xml results created for a report to the xml file stored on the system
    """
    date_created = models.DateField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    report_type = models.CharField(max_length=255, db_index=True)
    xml_filename = models.CharField(max_length=255, db_index=True)

jsnetwork_project/users/views.py
# -*- coding: utf-8 -*-


from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

jsnetwork_project/templates/orders/generating_report.html
{% extends "base.html" %}
{% block title %}Success{% endblock %}

{% block content %}
  <h3>Report being generated for order #{{ order_id }}.</h3>
  <br/>
  <h5>This page will automatically refresh in a few seconds</h5>
  <br/>
  <div>Once your report is complete, you will be taken back to the orders screen where you can view the report.</div>
  <div  >Alternatively, you can <a href="{% url 'orders:index' %}">click here</a> to go back to the orders list now, and
  the button will turn blue when the order is ready once that page is reloaded.</div>
  {% if not order_processing_is_complete %}
    <script type="text/javascript">
      window.setTimeout(function () {
        location.reload();
    }, 10000); // refresh/redirect after a few seconds.
    </script>
  {% else %}
    <script type="text/javascript">
    window.setTimeout(function () {
      location.href = "{% url 'orders:index' %}";
  }, 8000); // refresh/redirect after 5 seconds.
    </script>

  {% endif %}
{% endblock content %}

jsnetwork_project/templates/orders/index.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Order List{% endblock %}

{%  block css %}
  {{ block.super }}
    <!-- DataTables -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
    .btn-primary btn-sm {
      color: #ffffff
    }
    </style>
{%  endblock css %}


{% block content %}

<p>
  <a class="btn btn-primary" href="{% url 'orders:order_new' %}" role="button">Add a new order</a>
  <a class="btn btn-info" href="{% url 'orders:search_prev' %}" role="button">Search prev order</a>
</p>

<div class="card">
{#  <div class="card-header">#}
{#    Options for latest orders:#}
{#  </div>#}
  <div class="card-body">
{#    <div style="padding-bottom:10px;"><a href="#" class="btn btn-info">Merge Selected</a></div>#}
    {% if latest_order_list %}
        <table id="ordertable" class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>Order time</th>
                <th width="30%">Order details</th>
                <th>Reporting/order options</th>
            </tr>
        </thead>
        {% for order in latest_order_list %}
            <tr valign="middle">
                <td><input type="checkbox" name="checks[]" value="{{ order.id }}" /></td>
                <td style="padding-right: 1em">
                    {{ order.created|date:'Y-m-d H:i' }}
                </td>

                <td>{{ order.client.client_name }} -

                  <a data-toggle="tooltip" data-placement="top" title="{% for searchname in order.searchname_set.all %}{{ searchname }} {% endfor %}" href="{% url 'orders:detail' order.id %}">
                    {{ order.title_number }}
                    {% if order.internal_tracking_num %}[{{ order.internal_tracking_num }}]{% endif %}
                  </a>
                </td>
                <td>
                  {% with order.generatedreport_set.all|first as rs %}
                    {% if 'Y' in rs.name_select_ready %}
                      <a class="btn btn-primary btn-sm" href="{% url 'orders:name_select' order.id %}">NAMES</a>
                      |
                    {% endif %}
                    {% if rs.merged_report_filename %}
                      <a class="btn btn-primary btn-sm" href="{% url 'orders:view_report' rs.merged_report_filename %}">FULL</a>
                    {% else %}
                      <a class="btn btn-secondary btn-sm" href="#">FULL</a>
                    {% endif %}
                    {% if rs.state_filename %}
                      <div class="btn-group" role="group">
                        <button id="btnGroupDropExcel" type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          EXCEL
                        </button>
                        <div class="dropdown-menu" aria-labelledby="btnGroupDropExcel">
                          <a class="dropdown-item" href="{% url 'orders:csv_report' order.id %}">JSN Only</a>
                          {% if rs.state_hv_filename %}
                            <a class="dropdown-item" href="{% url 'orders:csv_report_high_value' order.id%}">JSN Only High Value</a>
                          {% endif %}
                          <a class="dropdown-item" href="{% url 'pdftools:results_comparison' order.id %}">Comparison</a>
                        </div>
                      </div>
                    {% endif %}
                    <a href="{% url 'orders:run_search' order.id 'full' %}" data-regenratereport="true"><i class="fa fa-refresh"></i></a>
                    |
                    {% if rs.state_filename %}
                      {% if "," in rs.state_filename %}
                        <a class="btn btn-primary btn-sm" href="{% url 'orders:merge_and_view' order.id 'state_report' %}">SC</a>
                      {% else %}

                        {% if rs.state_hv_filename %}
                          <div class="btn-group" role="group">
                            <button id="btnGroupDropSC" type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              SC
                            </button>
                            <div class="dropdown-menu" aria-labelledby="btnGroupDropSC">
                              <a class="dropdown-item" href="{% url 'orders:view_report' rs.state_filename %}">Regular Report</a>
                              <a class="dropdown-item" href="{% url 'orders:view_report' rs.state_hv_filename %}">High Value Report</a>
                            </div>
                          </div>
                        {% else %}
                            <a class="btn btn-primary btn-sm" href="{% url 'orders:view_report' rs.state_filename %}">SC</a>
                        {% endif %}


                      {% endif %}
                    {% else %}
                      <a class="btn btn-secondary btn-sm" href="#">SC</a>
                    {% endif %}
                    <a href="{% url 'orders:run_search' order.id 'state_report' %}" data-regenratereport="true"><i class="fa fa-refresh"></i></a>
                    |
                    {% if rs.bankruptcy_filename %}
                      {% if "," in rs.bankruptcy_filename %}
                        <a class="btn btn-primary btn-sm" href="{% url 'orders:merge_and_view' order.id 'bankruptcy' %}">BK</a>
                      {% else %}
                        <a class="btn btn-primary btn-sm" href="{% url 'orders:view_report' rs.bankruptcy_filename %}">BK</a>
                      {% endif %}
                    {% else %}
                      <a class="btn btn-secondary btn-sm" href="#">BK</a>
                    {% endif %}
                    <a href="{% url 'orders:run_search' order.id 'bankruptcy' %}" data-regenratereport="true"><i class="fa fa-refresh"></i></a>
                    |
                    {% if rs.usdc_filename %}
                      {% if "," in rs.usdc_filename %}
                        <a class="btn btn-primary btn-sm" href="{% url 'orders:merge_and_view' order.id 'usdc' %}">US</a>
                      {% else %}
                        <a class="btn btn-primary btn-sm" href="{% url 'orders:view_report' rs.usdc_filename %}">US</a>
                      {% endif %}
                    {% else %}
                      <a class="btn btn-secondary btn-sm" href="#">US</a>
                    {% endif %}
                    <a href="{% url 'orders:run_search' order.id 'usdc' %}" data-regenratereport="true"><i class="fa fa-refresh"></i></a>
                    |
                    {% if rs.patriot_filename %}
                      {% if "," in rs.patriot_filename %}
                        <a class="btn btn-primary btn-sm" href="{% url 'orders:merge_and_view' order.id 'patriot' %}">PT</a>
                      {% else %}
                        <a class="btn btn-primary btn-sm" href="{% url 'orders:view_report' rs.patriot_filename %}">PT</a>
                      {% endif %}
                    {% else %}
                      <a class="btn btn-secondary btn-sm" href="#">PT</a>
                    {% endif %}
                    <a href="{% url 'orders:run_search' order.id 'patriot' %}" data-regenratereport="true"><i class="fa fa-refresh"></i></a>
                    {% if rs.merged_report_filename %}
                      |
                      <a class="btn btn-dark btn-sm" href="{% url 'orders:reorder' order.id %}" data-reorderreport="true">Order Cont.</a>
                    {% endif %}
                  {% endwith %}
                </td>
            </tr>
        {% endfor %}
    </table>
    {% else %}
        <p>No orders are available.</p>
    {% endif %}
    <h1>Upload XML to generate report</h1>
    <form action="{% url 'orders:xml_to_base64' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <select name="option" id="option">
          <option value="BankruptcyReport">BankruptcyReport</option>
        </select><br><br>
        <input type="file" name="file" accept=".xml">
        <button type="submit">Convert</button>
        
    </form>
  </div>

</div>

{% endblock content %}

{% block custom-javascript %}
  {{ block.super }}
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>
    <script>
      var table = $('#ordertable').DataTable({
        "drawCallback": function( settings ) {
          $('[data-toggle="tooltip"]').tooltip()
        },
        "language": {
          "search": "Filter orders:"
        },
        "order": [[ 0, "desc" ]]
      });
    </script>
    <script>
      // https://stackoverflow.com/questions/25329508/use-simple-javascript-to-confirm-deletion-in-django
      $('*[data-regenratereport="true"]').on('click', function() {
        return confirm("Are you sure you want to (re)generate this report?");
      });
      $('*[data-reorderreport="true"]').on('click', function() {
        return confirm("This will place a reorder for this order. Are you sure you sure?");
      });
    </script>
{% endblock custom-javascript %}

jsnetwork_project/templates/orders/quick_search.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Quick search{% endblock %}

{% block js %}

{% endblock js %}

{%  block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <!-- DataTables -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">


{%  endblock css %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h4>Search for a name:</h4>
            {{ search_form.non_field_errors }}
            <form action="{%  url 'orders:quick_search' %}" method="get">
                <div>
                    {{ search_form.as_p }}
                </div>
                <div>
                    <button type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
    <div>
        {% if debug_message %}
            {{ debug_message }}
        {%  endif %}
    </div>
    <div>
        <!-- matched case list  -->
        {% if matched_cases %}
            <div>Displaying all open cases with judgments:</div>
            {% for matched_case in matched_cases %}
{#                <div>{{ matched_case }}: {{ matched_case.judgment_set.all()[0].first_judgment_amt }}</div>#}
                <div>{{ matched_case }}: {{ matched_case.first_judgment_amt }}</div>
            {%  endfor %}

        {%  endif %}
    </div>

    {% block custom-javascript %}
    <script>
        $(document).ready(function() {
            $('#nametable').DataTable({
              "language": {
                "search": "Filter records:"
              }
        });
    } );
    </script>
    {% endblock %}

{% endblock content %}

jsnetwork_project/templates/orders/results_comparison.html
{% extends "base.html" %}
{% load static %}

{% block title %}Results Comparison{% endblock %}

{% block content %}
  {% if order_id %}
    <h4>This will compare JSN results to CJ or State results, and provide an updated spreadsheet.</h4>
    <h4>Attach the PDF with these results below and click Submit to complete the process.</h4>
    <div>The compiled .xlsx file will be downloaded automatically</div>
    <div style="margin-top:50px"></div>
    <form action="{% url 'pdftools:cj_comparison' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p>
        <h5>Choose Charles Jones File:</h5>
        <input type="file" name="cj_file" />
      </p>
      <p>
        <h5>Choose State Capital File:</h5>
        <input type="file" name="sc_file" />
      </p>
      <p style="margin-top:50px;">
        <input type="submit" />
      </p>
      <input type="hidden" name="order_id" value="{{ order_id }}">
    </form>
  {% endif %}
{% endblock content %}

jsnetwork_project/templates/orders/search_prev.html
{% extends "base.html" %}
{% block title %}Order Detail{% endblock %}

{% block content %}
  {% if not user_search_info %}
    <h4>Please enter your client number below to pull up a previous search</h4>
    <form action="{% url 'orders:search_prev' %}" method="post">
      {% csrf_token %}
      <p>
        <label>Client file number:</label>
        <input name="client_num" />
      </p>
      <p>
        <input type="submit" name="action" value="Search"/>
      </p>
    </form>
  {% endif %}
{% endblock content %}