config/urls.py
# -*- coding: utf-8 -*-


from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf import settings # new
from  django.conf.urls.static import static #new

# fix problem with admin section being inacessible on production
# https://github.com/pydanny/cookiecutter-django/issues/162
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include(('jsnetwork_project.users.urls','users'), namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^nameviewer/', include(('nameviewer.urls', 'nameviewer'), namespace='nameviewer')),
    url(r'^usermgmt/', include(('usermgmt.urls', 'usermgmt'), namespace='usermgmt')),
    url(r'^pdftools/', include(('pdftools.urls', 'pdftools'), namespace='pdftools')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

# set properties on the admin site - no need to define a custom template any more
# http://stackoverflow.com/questions/4938491/django-admin-change-header-django-administration-text
admin.site.site_header = 'Judgment Search Network Administration'
admin.site.site_title = 'JSN Admin'

jsnetwork_project/users/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

nameviewer/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^common_names/$', views.common_names, name='common_names'),
    url(r'^common_names/(?P<name_type>\w+)$', views.common_names, name='common_names'),
    url(r'^common_names/(?P<name_type>\w+)/(?P<name_select>\w+)$', views.common_names, name='common_names'),
    url(r'^new_name_alias/(?P<name_type>\w+)$', views.new_name_alias, name='new_name_alias'),
    url(r'^new_name_alias/(?P<name_type>\w+)/(?P<name_select>\w+)/(?P<new_name_alias>\w+)$', views.new_name_alias, name='new_name_alias'),
]

jsnetwork_project/users/models.py
# -*- coding: utf-8 -*-


from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

nameviewer/models.py
from django.db import models

# Create your models here.

jsnetwork_project/users/views.py
# -*- coding: utf-8 -*-


from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

nameviewer/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required

from orders.models import Forename, Surname

from . import helpers

# Create your views here.
@login_required
def index(request):
    """
    Allow a logged in user to generate name variations for a first and/or last name
    :param request:
    :return:
    """

    name_to_search = request.GET.get('name','lloyd') # may want to set default param too
    # print('Name: {}'.format(type(name_to_search)))
    name_type = request.GET.get('rad')

    forename_namematch_list = []
    surname_namematch_list = []
    name_combinations = []

    second_name_to_search = request.GET.get('second_name')
    if second_name_to_search:
        name_filter = helpers.get_forename_results(request, name_to_search) # @TODO: cleanup unused call

        forename_filter = name_filter
        for fn in forename_filter.qs:
            forename_namematch_list.append(fn.name_match)

        # surname_filter = _get_surname_results(request, second_name_to_search)
        surname_list = Surname.objects.filter(name=second_name_to_search)
        # surname_filter = SurnameFilter(request.GET, queryset=surname_list)

        for sn in surname_list:
            surname_namematch_list.append(sn.name_match)
        print(('Lists count: forename {}, surname {}'.format(len(forename_namematch_list), len(surname_list))))

        # name_combinations = _make_name_combinations(forename_namematch_list, surname_namematch_list)
        name_combinations = helpers.make_name_combinations(forename_namematch_list, surname_namematch_list)
        # import itertools
        # name_combinations = list(itertools.product(forename_namematch_list, surname_namematch_list))
    else:
        if name_type == 'forename':
            name_filter = helpers.get_forename_results(request, name_to_search)
        else:
            name_filter = helpers.get_surname_results(request, name_to_search)

    context = {
        'filter': name_filter,
        'rad': name_type,
        'matched_forenames': forename_namematch_list,
        'matched_surnames': surname_namematch_list,
        'name_combinations': name_combinations,
        'num_name_combs': len(name_combinations),
    }
    return render(request, 'nameviewer/index.html', context)

@login_required
def common_names(request, name_type=None, name_select=None):
    """
    Display a view with a list of common names for either surnames or forenames
    :param request: the http request object
    :param name_type: the type of view to return based on surname or forename
    :param name_select: the name to use for the lookup
    :return:
    """
    from django.conf import settings
    from nameviewer.helpers import get_name_match_score
    from nameviewer.utils import NameAliasUtils
    from orders.models import Surname, Forename

    if request.method == "POST":
        # process new alias preferences
        all_name_var_objs = NameAliasUtils.load_scored_names(name_select, name_type)
        all_name_variations = set([x.name_match for x in all_name_var_objs])
        active_name_variations = request.POST.getlist('name-variation-select[]')
        inactive_name_variations = list(all_name_variations - set(active_name_variations))
        if name_type == 'surname':
            Surname.objects.using(settings.NAMESEARCH_DB).filter(name=name_select.lower()).filter(name_match__in=active_name_variations).update(deleted='')
            Surname.objects.using(settings.NAMESEARCH_DB).filter(name=name_select.lower()).filter(name_match__in=inactive_name_variations).update(deleted='Y')
        else:
            Forename.objects.using(settings.NAMESEARCH_DB).filter(name=name_select.lower()).filter(name_match__in=active_name_variations).update(deleted='N')
            Forename.objects.using(settings.NAMESEARCH_DB).filter(name=name_select.lower()).filter(name_match__in=inactive_name_variations).update(deleted='Y')

    names_list, scored_names = NameAliasUtils.load_common_names(name_type, name_select)
    if name_type == 'surname':
        name_match_score = int(get_name_match_score())
    else:
        name_match_score = int(get_name_match_score('FIRST_NAME'))
    context = {
        'common_names_list': names_list,
        'name_type': name_type,
        'name_select': name_select,
        'scored_names': scored_names,
        'score_threshold': name_match_score  # 'FIRST_NAME
    }
    return render(request, 'nameviewer/common_names.html', context)

@login_required
def new_name_alias(request, name_type=None, name_select=None, new_name_alias=None):
    """
    View to add a new name to the alias dictionary
    :param request: the request object
    :param name_type: type of name to add
    :param name_select: the base name to use for adding the new alias
    :param new_name_alias: the new alias to add to the base name
    :return:
    """
    from nameviewer.utils import NameAliasUtils

    NameAliasUtils.add_new_alias(name_type, name_select, new_name_alias)
    return common_names(request, name_type, name_select)

jsnetwork_project/templates/nameviewer/common_names.html
{% extends "base.html" %}
{% block title %}Common Names{% endblock %}

{% block css %}
  {{ block.super }}
    <style>
      .ms-list {
        height: 500px !important;
      }
    .custom-header {
      font-weight: bold;
    }
    .name-decoration {
      font-weight: bold;
      text-decoration: underline;
    }
    </style>
{% endblock css %}

{% block content %}
  <h3>
    <a {% if name_type == 'female' %}class="name-decoration"{% endif %} href="{% url 'nameviewer:common_names' 'female' %}">Female</a> |
    <a {% if name_type == 'male' %}class="name-decoration"{% endif %} href="{% url 'nameviewer:common_names' 'male' %}">Male</a> |
    <a {% if name_type == 'surname' %}class="name-decoration"{% endif %} href="{% url 'nameviewer:common_names' 'surname' %}">Surname</a>
  </h3>

  <h5>First, select a name from the list of the most common {{ name_type }} names:</h5>
  <p>
    <select class="js-example-basic-single">
      {% if not name_select %}
        <option value='' selected="selected"></option>
      {% endif %}
      {% for cn in common_names_list %}
        {% if name_select == cn %}
          <option value='{{ cn }}' selected="selected">{{ cn }}</option>
        {% else %}
          <option value='{{ cn }}'>{{ cn }}</option>
        {% endif %}
      {% endfor %}
    </select>
  </p>

  <p>*or*</p>
  <h5>Type a name into the box below if you want to lookup a non-common name.</h5>
  <input id="uncommon-name" name="uncommon-name" value="{% if name_select %}{{name_select}}{% endif %}"></input>&nbsp;<button class="js-uncommon-name-click">Search name</button>

  {% if scored_names %}
    <h5>Next, choose the names you want the system to include in searches below. Click submit to save your changes.</h5>
  {% endif %}
  {% if scored_names %}
  <div class="container">
    <div class="row">
      <div class="col">
          <form id="name_variants_form" action="{% url 'nameviewer:common_names' name_type name_select %}" method="post">
            {% csrf_token %}
            <select multiple="multiple" id="name-variation-select" name="name-variation-select[]">
                {% for sn in scored_names %}
                  {% if sn.score|add:"0" >= score_threshold %}
                    {% if sn.deleted == '' or sn.deleted == 'N' %}
                      <option value='{{ sn.name_match }}' selected>{{ sn.name_match }}</option>
                    {% else %}
                      <option value='{{ sn.name_match }}'>{{ sn.name_match }}</option>
                    {% endif %}
                  {% endif %}
                {% endfor %}

            </select>
            <div style="margin-top:15px">
              <input type="submit" value="Submit">
            </div>
          </form>
      </div>
      <div class="col">
        <h6>If the variation of the name you're looking for isn't shown to the left, you can add a variation below:</h6>
        <p>
          <input id="new-alias" name="new-alias"></input>&nbsp;<button class="js-new-name">Add name alias</button>
        </p>
      </div>
    </div>
    {% endif %}
  </div>

{% endblock content %}

{% block custom-javascript %}
<script>
  $(document).ready(function() {
      {% if scored_names %}
        $('#name-variation-select').multiSelect({
          selectableHeader: "<div class='custom-header'>Inactive Names</div>",
          selectionHeader: "<div class='custom-header'>Active Names</div>",
          selectableOptgroup: true,
          cssClass: "jquery-multiselect",
          autoSize : false
        });
      {% endif %}
      $('.js-example-basic-single').select2();
  });
  $('.js-example-basic-single').on('change', function() {
    var selected_name = 'smith';
    if (this.value) { selected_name = this.value; }
    var url = "{% url 'nameviewer:common_names' name_type %}" + "/"  + selected_name;
    window.location = url;
  });

  function inputHandler() {
    var entered_name = 'sean';
    var name_input = document.getElementById("uncommon-name");
    if (name_input.value) { entered_name = name_input.value; }
    var url = "{% url 'nameviewer:common_names' name_type %}" + "/"  + entered_name;
    window.location = url;
  }

  function newNameHandler() {
    var name_selected = document.getElementById("uncommon-name");  // original name entered
    if (name_selected.value) { entered_name = name_selected.value; }
    var name_input = document.getElementById("new-alias");  // name alias to add
    if (name_input.value) { alias_name = name_input.value; }
    var url = "{% url 'nameviewer:new_name_alias' name_type %}" + "/{{name_select}}/" + alias_name;
    window.location = url;
  }

  $('.js-uncommon-name-click').on('click', inputHandler);

  $('#uncommon-name').on('keydown', function(e) {
    if (e.which == 13) {
        inputHandler();
    }
  });

  $('.js-new-name').on('click', newNameHandler);

</script>
{% endblock custom-javascript %}

jsnetwork_project/templates/nameviewer/index.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Namesearch Viewer{% endblock %}

{% block js %}

{% endblock js %}

{%  block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <!-- DataTables -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">


{%  endblock css %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h4>Search for a name:</h4>
            {{ search_form.non_field_errors }}
            <form action="{%  url 'nameviewer:index' %}" method="get">
                <div>
                    <label for="id_rad_0"><input type="radio" id="id_rad_0" value="forename"
                                                {% if rad != "surname" %} {{ "checked" }} {% endif %}
                                                 name="rad" /> Forname</label>
                </div>
                <div>
                    <label for="id_rad_1"><input type="radio" id="id_rad_1" value="surname"
                                                {% if rad == "surname" %} {{ "checked" }} {% endif %}
                                                 name="rad" /> Surname</label>
                </div>
                <div>
                    {{ filter.form }}
                    <input type="text" name="second_name" placeholder="Optional second name" />
                </div>
                <div>
                    <button type="submit">Submit</button>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <table id="nametable" class="table table-striped">
                <thead>
                    <th>Name</th>
                    <th>Name Match</th>
                    <th>Score</th>
                </thead>
                {% for name_obj in filter.qs %}
                <tr>
                    <td>{{ name_obj.name }}</td>
                    <td>{{ name_obj.name_match }}</td>
                    <td>{{ name_obj.score }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div>
        <!-- name match list if two entries were supplied -->
        {% if matched_forenames %}
            <div>Displaying all name matches:</div>
            {% for name in name_combinations %}
                <div>{{ name.0 }} {{ name.1 }}</div>
            {%  endfor %}

        {%  endif %}
    </div>

    {% block custom-javascript %}
    <script>
        $(document).ready(function() {
            $('#nametable').DataTable({
              "language": {
                "search": "Filter records:"
              }
        });
    } );
    </script>
    {% endblock %}

{% endblock content %}