config/urls.py
# -*- coding: utf-8 -*-


from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf import settings # new
from  django.conf.urls.static import static #new

# fix problem with admin section being inacessible on production
# https://github.com/pydanny/cookiecutter-django/issues/162
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include(('jsnetwork_project.users.urls','users'), namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^nameviewer/', include(('nameviewer.urls', 'nameviewer'), namespace='nameviewer')),
    url(r'^usermgmt/', include(('usermgmt.urls', 'usermgmt'), namespace='usermgmt')),
    url(r'^pdftools/', include(('pdftools.urls', 'pdftools'), namespace='pdftools')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

# set properties on the admin site - no need to define a custom template any more
# http://stackoverflow.com/questions/4938491/django-admin-change-header-django-administration-text
admin.site.site_header = 'Judgment Search Network Administration'
admin.site.site_title = 'JSN Admin'

jsnetwork_project/users/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

usermgmt/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^client_edit/(?P<client_id>[0-9]+)$', views.index, name='client_edit'),
    url(r'^client_add/(?P<client_id>[0-9]+)/(?P<add_id>[0-9]+)$', views.index, name='client_add'),
    url(r'^new_user/$', views.new_user, name='new_user'),
]

jsnetwork_project/users/models.py
# -*- coding: utf-8 -*-


from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

usermgmt/models.py
from django.db import models

# Create your models here.

usermgmt/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Provide a valid email address.')

    class Meta:
        User = get_user_model()
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

jsnetwork_project/users/views.py
# -*- coding: utf-8 -*-


from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

usermgmt/views.py
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.shortcuts import render

from orders.models import Client, UserClient
from orders.utils import OrderUtils

# Create your views here.

@login_required
def index(request, client_id=0, add_id=0):
    current_user = request.user
    if add_id:
        u = UserClient.objects.get_or_create(client_id=client_id, user_id=add_id)
        # u = UserClient(client_id=client_id, user_id=add_id)
        # u.save()

    user_client_id_list = OrderUtils.get_user_client_ids(current_user)
    user_is_superuser = current_user.is_superuser and current_user.is_active

    if not user_is_superuser:
        sql = "Select * from orders_client where client_id IN (%s) order by client_name"
        user_clients_list = Client.objects.raw(sql, [user_client_id_list])
    else:
        user_clients_list = Client.objects.all().order_by('client_name')
    context = {'clients': user_clients_list}

    # only run this if a client has been selected to populate the right-half of the screen
    if client_id:
        User = get_user_model()

        # assigned_users = UserClient.objects.filter(client_id=client_id)
        sql = "select * from users_user INNER JOIN orders_userclient ON orders_userclient.user_id = users_user.id where orders_userclient.client_id = (%s)"
        assigned_users = User.objects.raw(sql, [client_id])
        context['assigned_users'] = assigned_users
        # context['my_perms'] = current_user.user_permissions.all()

        a_ids = []
        for x in assigned_users:
            a_ids.append(x.id)

        users_list = User.objects.filter(is_superuser=0).filter(is_active=1)
        # sql = "select * from users_user INNER JOIN orders_userclient ON orders_userclient.user_id = users_user.id where orders_userclient.client_id = (%s) and orders_userclient.user_id not in (%s)"
        # unassigned_users = User.objects.raw(sql, [client_id, a_ids])
        # context['users'] = unassigned_users
        context['users'] = users_list
        context['selected_client'] = Client.objects.get(id=client_id)

    if not client_id:
        return render(request, 'usermgmt/userclient_edit.html', context)
    else:
        return render(request, 'usermgmt/userclient_useredit.html', context)

def new_user(request):
    from django.contrib.auth import login, authenticate
    from django.contrib import messages
    from django.shortcuts import render, redirect
    from .forms import SignUpForm

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            # login(request, user)  # this will log you in as that user!
            # return redirect('home')
            # @TODO: show success message
            form = SignUpForm()
            messages.success(request, 'User registration for {} was successful'.format(username))
    else:
        form = SignUpForm()
    return render(request, 'usermgmt/signup.html', {'form': form})

jsnetwork_project/templates/usermgmt/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}New User Registration{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-7">
        <h2>New user registration</h2>
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
            <p>
              {{ field.label_tag }}<br>
              {{ field }}
              {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
              {% endfor %}
            </p>
          {% endfor %}
          <button type="submit">Register</button>
        </form>
      </div>
      <div class="col">
        <h3>New user registration instructions</h3>
        <div>Fill out the information requested to the the left.</div>
        <div>A username and email are required along with a password.</div>
        <div>Once the user is created, the client management tab will let you associate the user to one or more clients.</div>
      </div>
    </div>
  </div>
{% endblock %}

jsnetwork_project/templates/usermgmt/userclient_edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}Client User List Editor{% endblock %}

{%  block css %}
  {{ block.super }}
    <!-- DataTables -->
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
    .btn-primary btn-sm {
      color: #ffffff
    }
    </style>
{%  endblock css %}

{% block content %}
<div class="container">

{% if clients %}
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <h3>Clients List</h3>
        <div><h6>(Select one of the following to manage their users.)</h6></div>
        {% for client in clients %}
          <div><a href="{% url 'usermgmt:client_edit' client.id %}">{{ client.client_name }}</a></div>
{#          <div>foo</div>#}
        {% endfor %}
      </div>
      <div class="col-sm">
        {% block client_users %}
        {% endblock %}
      </div>
    </div>
  </div>
{% endif %}



</div>
{% endblock content %}

jsnetwork_project/templates/usermgmt/userclient_useredit.html
{% extends "usermgmt/userclient_edit.html" %}

{% if users %}
  {% block client_users %}
    <h3>{{ selected_client.client_name }} - Available Users</h3>
    <table id="clienttable" class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Login</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for u in users %}
        <tr>
          <td>{{ u.username }}</td>
          <td>{{ u.email }}</td>
          <td><a href="{% url 'usermgmt:client_add' selected_client.id u.id %}">Add</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    <div>&nbsp;</div>
    <h3>Assigned Users</h3>
    <table class="table table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Login</th>
          <th>Email</th>
        </tr>
      </thead>
      <tbody>
        {% for u in assigned_users %}
          <tr>
            <td>{{ u.username }}</td>
            <td>{{ u.email }}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="2">No users have been assigned.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  {% endblock %}
{% else %}
  No users are available.
{% endif %}

{% block custom-javascript %}
    <script>
        $(document).ready(function() {
            $('#clienttable').DataTable({
              "language": {
                "search": "Filter users:"
              },
              "order": [[ 0, "desc" ]],
              "pageLength": 5
        });
    } );
    </script>
{% endblock %}