config/urls.py
# -*- coding: utf-8 -*-


from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.conf import settings # new
from  django.conf.urls.static import static #new

# fix problem with admin section being inacessible on production
# https://github.com/pydanny/cookiecutter-django/issues/162
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include(('jsnetwork_project.users.urls','users'), namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^nameviewer/', include(('nameviewer.urls', 'nameviewer'), namespace='nameviewer')),
    url(r'^usermgmt/', include(('usermgmt.urls', 'usermgmt'), namespace='usermgmt')),
    url(r'^pdftools/', include(('pdftools.urls', 'pdftools'), namespace='pdftools')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

# set properties on the admin site - no need to define a custom template any more
# http://stackoverflow.com/questions/4938491/django-admin-change-header-django-administration-text
admin.site.site_header = 'Judgment Search Network Administration'
admin.site.site_title = 'JSN Admin'

jsnetwork_project/users/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

nameviewer/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^common_names/$', views.common_names, name='common_names'),
    url(r'^common_names/(?P<name_type>\w+)$', views.common_names, name='common_names'),
    url(r'^common_names/(?P<name_type>\w+)/(?P<name_select>\w+)$', views.common_names, name='common_names'),
    url(r'^new_name_alias/(?P<name_type>\w+)$', views.new_name_alias, name='new_name_alias'),
    url(r'^new_name_alias/(?P<name_type>\w+)/(?P<name_select>\w+)/(?P<new_name_alias>\w+)$', views.new_name_alias, name='new_name_alias'),
]

orders/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^order_new/', views.order_new, name='order_new'),
    url(r'^(?P<order_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^quick_search/', views.quick_search, name='quick_search'),
    url(r'^quick_order/', views.quick_order, name='quick_order'),
    url(r'^run_search/(?P<order_id>[0-9]+)/(?P<report_type>\w+)/$', views.run_search, name='run_search'),
    url(r'^settings/', views.settings, name='settings'),
    url(r'^view_pdf/(?P<filename>.+)$', views.view_report, name="view_report"),
    url(r'^xml-to-base64/$', views.xml_to_base64, name="xml_to_base64"),
    url(r'^csv_report/(?P<order_id>.+)$', views.csv_report, name="csv_report"),
    url(r'^csv_report_high_value/(?P<order_id>.+)$', views.csv_report_high_value, name="csv_report_high_value"),
    url(r'^merge_and_view/(?P<order_id>[0-9]+)/(?P<report_type>\w+)$', views.merge_and_view_pdf, name="merge_and_view"),
    url(r'^order_status/(?P<order_id>[0-9]+)/(?P<report_type>\w+)$', views.order_status, name='order_status'),
    url(r'^reorder/(?P<order_id>[0-9]+)$', views.reorder, name='reorder'),
    url(r'^name_select/(?P<order_id>[0-9]+)$', views.select_names, name='name_select'),
    url(r'^name_select_view_pdf/', views.name_select_view_pdf, name='name_select_view_pdf'),
    url(r'^search_prev/', views.search_prev, name='search_prev'),
]

usermgmt/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^client_edit/(?P<client_id>[0-9]+)$', views.index, name='client_edit'),
    url(r'^client_add/(?P<client_id>[0-9]+)/(?P<add_id>[0-9]+)$', views.index, name='client_add'),
    url(r'^new_user/$', views.new_user, name='new_user'),
]

jsnetwork_project/users/models.py
# -*- coding: utf-8 -*-


from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

orders/models.py
# noinspection PyPackageRequirements


from django.db import models

from core.models import TimeStampedModel


# Create your models here.
class Client(models.Model):
    """
    A class for representing a client model
    """
    client_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    client_id = models.CharField(max_length=50, blank=True)  # quickbooks number
    addr1 = models.CharField(max_length=100, blank=True, default=None, null=True)
    addr2 = models.CharField(max_length=100, blank=True, default=None, null=True)
    city = models.CharField(max_length=50, blank=True, default=None, null=True)
    state = models.CharField(max_length=2, blank=True, default=None, null=True)
    zip = models.CharField(max_length=10, blank=True, default=None, null=True)

    def __str__(self):
        return self.client_name


class Order(TimeStampedModel):
    """
    A simple class for representing an order in the system
    """
    EMAIL = 'EM'
    WEB_SERVICES = 'WB'
    TELEPHONE = 'TL'
    ORDER_SOURCE_CHOICES = (
        (EMAIL, 'Email'),
        (TELEPHONE, 'Telephone'),
        (WEB_SERVICES, 'Web Services'),
    )
    order_method = models.CharField(max_length=2, choices=ORDER_SOURCE_CHOICES, default=EMAIL)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)  # each order is reference to a single client
    title_number = models.CharField(max_length=20, verbose_name='Client file number')
    is_reorder = models.BooleanField(default=False)
    internal_tracking_num = models.CharField(max_length=100, blank=True, verbose_name='Internal number')
    date_invoiced = models.DateField(blank=True, default=None, null=True)


    def date_ordered(self):
        return self.created
    date_ordered.short_description = "Date ordered"

    def __str__(self):
        return self.title_number


class GeneratedReport(models.Model):
    """
    A simple class for representing generated reports in the system
    """
    bankruptcy_filename = models.CharField(max_length=255)
    usdc_filename = models.CharField(max_length=255)
    state_filename = models.CharField(max_length=255)
    state_hv_filename = models.CharField(max_length=255, default=None, null=True)
    cover_filename = models.CharField(max_length=255, blank=True, default=None, null=True)
    docket_list_filename = models.CharField(max_length=255, blank=True, default=None, null=True)
    patriot_filename = models.CharField(max_length=1000, blank=True, default=None, null=True)
    merged_report_filename = models.CharField(max_length=255, blank=True)
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE) # each generated report is references to a single order
    num_bankruptcy_matches = models.IntegerField(blank=True, default=None, null=True)
    num_usdc_matches = models.IntegerField(blank=True, default=None, null=True)
    num_state_matches = models.IntegerField(blank=True, default=None, null=True)
    num_state_hv_matches = models.IntegerField(blank=True, default=None, null=True)
    num_patriot_matches = models.IntegerField(blank=True, default=None, null=True)
    name_select_ready = models.CharField(max_length=1, blank=True, default=None, null=True)

    def __str__(self):
        return "Reports generated (b,u,s,p): {} - {} - {}".format(self.bankruptcy_filename, self.usdc_filename,
                                                                  self.state_filename, self.patriot_filename)


class SearchName(models.Model):
    """
    A class for representing the data supplied by a client for a judgment search
    """
    order = models.ForeignKey(Order, on_delete=models.CASCADE) # each search name is referenced to a single order
    first_name = models.CharField(max_length=100, blank=True, verbose_name='First Name')
    middle_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    suffix = models.CharField(max_length=20, blank=True)
    is_company = models.BooleanField(default=False)
    company_name = models.CharField(max_length=100, blank=True)
    company_type = models.CharField(max_length=20, blank=True) # make a choice
    address1 = models.CharField(max_length=100, blank=True)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    zip = models.CharField(max_length=10, blank=True)
    search_from = models.DateField()
    search_to = models.DateField()
    name_qualifier = models.CharField(max_length=20, blank=True)
    exact_name_match = models.BooleanField(default=False)
    additional_notes = models.TextField(blank=True)
    report_name = models.CharField(max_length=100, blank=True)
    high_value_search = models.BooleanField(default=False)
    
    def __unicode__(self):
        from collections import defaultdict
        if self.first_name != "":
            name = "{} {} {}".format(self.first_name, self.middle_name, self.last_name)
        elif self.company_name != "":
            name = self.company_name
        return name
    
    def __str__(self):
        from collections import defaultdict
        if self.first_name != "":
            name = "{} {} {}".format(self.first_name, self.middle_name, self.last_name)
        elif self.company_name != "":
            name = self.company_name
        return name

# namesearch models
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.


class NameBase(models.Model):
    """
    A class for representing a forename or surname as provided by IMage Partners
    Specifying an arbitrary column as a primary key since this is a readonly table
    """
    name = models.CharField(max_length=255)
    name_match = models.CharField(max_length=255, primary_key=True)
    score = models.DecimalField(max_digits=10, decimal_places=0)
    deleted = models.CharField(max_length=1)
    nickname = models.CharField(max_length=1)

    class Meta:
        managed = False
        abstract = True
        ordering = ['name']


class Forename(NameBase):
    """
    A class for representing forenames as provided by the name alias database
    """
    class Meta(NameBase.Meta):
        db_table = 'forenames'


class Surname(NameBase):
    """
    A class for representing surnames as provided by the name alias database
    """
    class Meta(NameBase.Meta):
        db_table = 'surnames'


class UserClient(models.Model):
    """
    A custom django user model which provides some additional flexibility not present in the base model
    Much easier to override this at the beginning of the app's development than trying to retrofit something in later on!
    """
    from config.settings.common import AUTH_USER_MODEL as user_model
    client = models.ForeignKey(Client, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(user_model, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.user.username + " - " + self.client.client_name


class FilteredSearchNameList(models.Model):
    """
    Unused
    """
    name_list = models.TextField()
    date_created = models.DateField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)  # each filtered name list was generated based on an order
    name_search = models.CharField(max_length=255, db_index=True)  # this is the original name entered by the user


class NameReportHistory(models.Model):
    """
    A model for mapping the xml results created for a report to the xml file stored on the system
    """
    date_created = models.DateField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    report_type = models.CharField(max_length=255, db_index=True)
    xml_filename = models.CharField(max_length=255, db_index=True)

jsnetwork_project/users/views.py
# -*- coding: utf-8 -*-


from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

jsnetwork_project/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

jsnetwork_project/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Judgment Search Network{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block js %}
    {% endblock %}

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static '/css/multi-select.css' %}" media="screen" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" />

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
<!--      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">  -->
{#      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">#}
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="/">Judgment Search Network</a>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
                {% if user.is_authenticated %}
                    {% if perms.orders.add_order %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'orders:index' %}">Orders</a>
                    </li>
                    {%  endif %}
                {% endif %}
{#                {% if user.is_superuser %}#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'nameviewer:index' %}">Name View</a>#}
{#                    </li>#}
{#                {% endif %}#}
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'nameviewer:common_names' 'surname' %}">Common Names</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav pull-xs-right">
              {% if perms.orders.add_userclient %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    User/Client Mgmt
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'usermgmt:new_user' %}">User/Login Management</a>
                    <a class="dropdown-item" href="{% url 'usermgmt:index' %}">Client Management</a>
                  </div>
                </li>
              {% endif %}
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container" style="margin-top:10px;">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>&copy 2018 JSN.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script src="{% static '/js/bootstrap-confirmation.min.js' %}"></script>


      <!-- Your stuff: Third-party javascript libraries go here -->
      <script type="text/javascript" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
      <script src="{% static '/js/jquery.multi-select.js' %}" type="text/javascript"></script> <!-- http://loudev.com/#demos -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>  <!-- https://select2.org/getting-started/installation -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}

    {%  block custom-javascript %}
    {%  endblock custom-javascript %}
  </body>
</html>